on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chatgpt_review:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: ChatGPT explain code
        uses: cirolini/chatgpt-github-actions@v1.3
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "gpt-3.5-turbo" #optional
          openai_temperature: 0.5 #optional
          openai_max_tokens: 2048 #optional
          mode: file # file or patch
